// Interface automatically generated by schemas-to-ts

export interface OriginalUrls {
  url?: string;
}
export interface OriginalUrls_Plain {
  url?: string;
}

export interface OriginalUrls_NoRelations {
  url?: string;
}

