/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import paperTrail from "strapi-plugin-paper-trail/strapi-admin";
import adminEmailNotifications from "../../src/plugins/admin-email-notifications/strapi-admin";
import adminComments from "../../src/plugins/admin-comments/strapi-admin";
import stats from "../../src/plugins/stats/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "paper-trail": paperTrail,
    "admin-email-notifications": adminEmailNotifications,
    "admin-comments": adminComments,
    stats: stats,
  },
});
